### PR TITLE
Problem: there is no information about this project

### PR DESCRIPTION
**Pull request by taotetek**
Solution: Add a README, AUTHORS and CONTRIBUTORS document.

### CODE REVIEW

**Comment by fatih** [comment]
The name `gogozmq` has two `go` prefixes. Is that a correct naming? Why not `gozmq` ?

**Comment by taotetek** [comment]
@fatih "gozmq" was the name of the original golang binding for ZeroMQ.  We chose "gogozmq" on purpose to 1) indicate it's pure go 2) not stomp on the name of the previous one and 3) get to say "gogo" a lot which is a funny thing to say.

**Comment by fatih** [comment]
Hm not sure I like it, this will be the first package with such a naming :) But imho naming is a really hard thing and given the fact you described it above, this kinda makes sense :+1:

**Comment by hintjens** [comment]
You could call it geromq or gozmtp, or gomq. These are consistent with
existing pure-language stacks (jeromq, libzmtp, netmq)...

gogozmq is cute, which may be annoying at some point. :)

Just my 5c.

**Comment by fatih** [comment]
:+1: to gomq. I really much liked it. Short but still relevant.

**Pull request merged**
