### PR TITLE
Problem: CONTRIBUTING link is wrong

### PR DESCRIPTION
**Pull request by taotetek**
Solution: Fix it.

### CODE REVIEW

**Comment by sappo** [comment]
@taotetek sry I guess merging the other PR caused this one to have conflicts :(

**Comment by taotetek** [comment]
@sappo oh no worries - I'll follow up with a fix!  You're fast! ;)

**Comment by taotetek** [comment]
Let's just close this and I'll submit a new one.

**Comment by sappo** [comment]
I do love pushing that merge button ;)

**Pull request closed without merging**
